### ISSUE TITLE
为网站添加 RSS

### ISSUE THREAD

**Issue by yudi-corgi** [vimiix/ali-db-monthly#2]
网站对《数据库内核月报》的整理和检索让我能轻松找到相关文章，很有帮助。
考虑到它是一种月报的形式，请问是否可添加订阅功能（RSS）以达到通知的需求？

**Comment by vimiix** [comment]
👍不错的提议，后面有时间我支持一下，实现以后再回复你

**Comment by vimiix** [comment]
@yudi-corgi  已添加。
https://alidbmonthly.vimiix.com/rss

**Comment by yudi-corgi** [comment]
感谢采纳，已成功订阅。祝好！:pray:

**Comment by yudi-corgi** [comment]
感谢采纳，已成功订阅。祝好！🙏
